name: Daily Scrobble

on:
  schedule:
    - cron: "38 5 * * *"
      timezone: "Asia/Manila"
  workflow_dispatch:

jobs:
  scrobble:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - run: uv sync

      - name: Scrobble
        env:
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
          LASTFM_API_SECRET: ${{ secrets.LASTFM_API_SECRET }}
          LASTFM_USERNAME: ${{ secrets.LASTFM_USERNAME }}
          LASTFM_PASSWORD: ${{ secrets.LASTFM_PASSWORD }}
          BROWSER_JSON: ${{ secrets.BROWSER_JSON }}
        run: uv run scrobble_daily.py
